
development:
  adapter: postgresql
  encoding: unicode
  database: mailman_development
  pool: 5
  username: ecasilla
  password:
  host: "localhost"

  adapter: postgresql
  encoding: unicode
  database: mailman_test
  pool: 5
  username: mailman
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mailman_production
  pool: 5
  username: mailman
  password:
