---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app02
  domain: mail-man.co
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: 967775
  image_type: 512MB
  image_id: Ubuntu 12.04.3 x64
  security_groups:
  - mailman_production_default
  - mailman_production_web
  - mailman_production_app02
  - mailman_production_app
  - mailman_production_unicorn
  - mailman_production_nginx
  - mailman_production_db
  - mailman_production_postgresql
  - mailman_production_postgresql_master
  - mailman_production_collectd
  - mailman_production_monit
  external_host: 
  external_ip: 192.241.159.98
  internal_host: 
  internal_ip: 192.241.159.98
  zone: 
  provider: digital_ocean
  platform: linux
  root_device_type: 
- volumes: {}
  static_ips: {}
